#!/usr/bin/env python3
"""
Convert a PRISM study Excel workbook into study.js for the dashboard.
Supports multi-token message designs with significance flags.

Usage: python convert_study.py HIV_Study_Data.xlsx
Output: src/data/study.js (overwrites)
"""
import sys
import json
import openpyxl

SEGMENTS = [
    "TSP","CEC","TC","HF","PP","WE","PFF","HHN","MFL","VS",
    "UCP","FJP","HCP","HAD","HCI","GHI"
]

# Map spreadsheet column order to segment ID order if needed
# Default: identity (spreadsheet cols match segment IDs)
# Override this if spreadsheet uses a different column order
SPREADSHEET_COL_TO_SEG_ID = None  # Set to dict like {1:2, 2:8, ...} if reordering needed


def read_meta(wb):
    ws = wb["StudyMeta"]
    meta = {}
    for row in ws.iter_rows(min_row=2, max_col=2, values_only=True):
        if row[0] and row[1]:
            meta[str(row[0]).strip()] = row[1]
    return meta


def read_messages(wb):
    ws = wb["Messages"]
    msgs = {}
    for row in ws.iter_rows(min_row=2, max_col=5, values_only=True):
        if row[0] is None or str(row[0]).startswith("#"):
            continue
        msg_id = int(row[0])
        token_id = int(row[1]) if row[1] is not None else -1
        short_name = str(row[2] or "")
        theme = str(row[3] or "")
        text = str(row[4] or "")
        if msg_id not in msgs:
            msgs[msg_id] = {"id": msg_id, "shortName": short_name, "theme": theme, "tokens": {}}
        msgs[msg_id]["tokens"][token_id] = text
        if short_name:
            msgs[msg_id]["shortName"] = short_name
        if theme:
            msgs[msg_id]["theme"] = theme
    return msgs


def read_variant_text(wb):
    ws = wb["VariantText"]
    variants = {}
    for row in ws.iter_rows(min_row=2, max_col=2 + len(SEGMENTS), values_only=True):
        if row[0] is None or str(row[0]).startswith("#"):
            continue
        msg_id = int(row[0])
        token_id = int(row[1]) if row[1] is not None else -1
        seg_variants = {}
        for i, seg in enumerate(SEGMENTS):
            val = row[2 + i]
            if val:
                col_key = i + 1
                if SPREADSHEET_COL_TO_SEG_ID:
                    seg_key = SPREADSHEET_COL_TO_SEG_ID.get(col_key, col_key)
                else:
                    seg_key = col_key
                seg_variants[seg_key] = str(val)
        if msg_id not in variants:
            variants[msg_id] = {}
        variants[msg_id][token_id] = seg_variants
    return variants


def read_sop_matrix(wb, sheet_name):
    ws = wb[sheet_name]
    data = {}
    for row in ws.iter_rows(min_row=3, max_col=2 + len(SEGMENTS), values_only=True):
        if row[0] is None:
            continue
        msg_id = int(row[0])
        token_label = str(row[1] or "TOTAL").strip()
        values = []
        for i in range(len(SEGMENTS)):
            v = row[2 + i]
            values.append(round(float(v), 1) if v is not None else 0.0)
        if msg_id not in data:
            data[msg_id] = {}
        data[msg_id][token_label] = values
    return data


def read_sig_flags(wb, sheet_name):
    if sheet_name not in wb.sheetnames:
        return {}
    ws = wb[sheet_name]
    data = {}
    for row in ws.iter_rows(min_row=3, max_col=2 + len(SEGMENTS), values_only=True):
        if row[0] is None:
            continue
        msg_id = int(row[0])
        token_label = str(row[1] or "TOTAL").strip()
        flags = []
        for i in range(len(SEGMENTS)):
            v = row[2 + i]
            flags.append(int(v) if v is not None else 0)
        if msg_id not in data:
            data[msg_id] = {}
        data[msg_id][token_label] = flags
    return data


def read_segment_metrics(wb):
    ws = wb["SegmentMetrics"]
    headers = [str(c.value or "").strip() for c in ws[1]]
    metrics = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0] is None:
            continue
        code = str(row[0]).strip()
        d = {}
        for i, h in enumerate(headers):
            if i < len(row):
                d[h] = row[i]
        metrics[code] = d
    return metrics


def read_theme_colors(wb):
    if "ThemeColors" not in wb.sheetnames:
        return {}
    ws = wb["ThemeColors"]
    colors = {}
    for row in ws.iter_rows(min_row=2, max_col=2, values_only=True):
        if row[0] and row[1] and not str(row[0]).startswith("#"):
            colors[str(row[0]).strip()] = str(row[1]).strip()
    return colors


def build_study_js(meta, messages, variant_text, control_sop, variant_sop,
                   sig_control, sig_variant, seg_metrics, theme_colors):
    lines = []
    lines.append("// ═══════════════════════════════════════════════════════════════")
    lines.append(f"// STUDY-SPECIFIC — {meta.get('topic', 'Study')}")
    lines.append(f"// Client: {meta.get('client', '')}")
    lines.append("// AUTO-GENERATED by convert_study.py — Do not edit by hand.")
    lines.append("// ═══════════════════════════════════════════════════════════════")
    lines.append("")

    # Study meta
    lines.append("export const STUDY_META = {")
    for k in ["study_name", "client", "topic", "field_date", "n_messages", "n_tokens_per_message", "methodology"]:
        v = meta.get(k, "")
        lines.append(f'  {k}: {json.dumps(v)},')
    lines.append("};")
    lines.append("")

    # Messages with tokens and variants
    lines.append("export const MESSAGES = [")
    for msg_id in sorted(messages.keys()):
        msg = messages[msg_id]
        tokens_obj = msg["tokens"]
        # Build tokens array
        token_entries = []
        for tk in sorted(tokens_obj.keys()):
            label = "core" if tk == 0 else f"token{tk}" if tk > 0 else "aggregate"
            text = tokens_obj[tk]
            # Get variant text for this token
            vt = variant_text.get(msg_id, {}).get(tk, {})
            vt_str = json.dumps(vt) if vt else "{}"
            token_entries.append(f'      {{id:{tk},label:{json.dumps(label)},text:{json.dumps(text)},variants:{vt_str}}}')
        tokens_str = ",\n".join(token_entries)
        lines.append(f'  {{id:{msg_id},shortName:{json.dumps(msg["shortName"])},theme:{json.dumps(msg["theme"])},')
        lines.append(f'    tokens:[\n{tokens_str}\n    ]}},')
    lines.append("];")
    lines.append("")

    # SoP matrices
    for name, sop_data in [("CONTROL_SOP", control_sop), ("VARIANT_SOP", variant_sop)]:
        lines.append(f"export const {name} = {{")
        for msg_id in sorted(sop_data.keys()):
            tokens = sop_data[msg_id]
            lines.append(f"  {msg_id}: {{")
            for token_label, values in tokens.items():
                lines.append(f"    {json.dumps(token_label)}: {json.dumps(values)},")
            lines.append("  },")
        lines.append("};")
        lines.append("")

    # Sig flags
    for name, sig_data in [("SIG_CONTROL", sig_control), ("SIG_VARIANT", sig_variant)]:
        if not sig_data:
            lines.append(f"export const {name} = {{}};")
        else:
            lines.append(f"export const {name} = {{")
            for msg_id in sorted(sig_data.keys()):
                tokens = sig_data[msg_id]
                lines.append(f"  {msg_id}: {{")
                for token_label, flags in tokens.items():
                    lines.append(f"    {json.dumps(token_label)}: {json.dumps(flags)},")
                lines.append("  },")
            lines.append("};")
        lines.append("")

    # Segment metrics
    lines.append("export const STUDY_METRICS = {")
    for code in SEGMENTS:
        if code not in seg_metrics:
            continue
        m = seg_metrics[code]
        roi = float(m.get("roi", 0) or 0)
        high_roi = int(float(m.get("highRoi", 0) or 0))
        supporters = int(float(m.get("supporters", 0) or 0))
        activation = int(float(m.get("activation", 0) or 0))
        influence = int(float(m.get("influence", 0) or 0))
        persuad = [
            int(float(m.get("persuad_strong_support", 0) or 0)),
            int(float(m.get("persuad_lean_support", 0) or 0)),
            int(float(m.get("persuad_persuadable", 0) or 0)),
            int(float(m.get("persuad_lean_oppose", 0) or 0)),
            int(float(m.get("persuad_strong_oppose", 0) or 0)),
        ]
        # Pre/post metrics
        prepost = {}
        for i in range(1, 5):
            pre = m.get(f"prepost_key{i}_pre")
            post = m.get(f"prepost_key{i}_post")
            label = m.get(f"prepost_key{i}_label")
            if pre is not None and post is not None and label:
                key = f"pp{i}"
                prepost[key] = [float(pre), float(post)]
        lines.append(f"  {code}: {{roi:{roi},highRoi:{high_roi},supporters:{supporters},activation:{activation},influence:{influence},persuadability:{json.dumps(persuad)},prePost:{json.dumps(prepost)}}},")
    lines.append("};")
    lines.append("")

    # Pre/post metric labels (extracted from first segment's data)
    lines.append("export const PREPOST_METRICS = [")
    first_seg = next(iter(seg_metrics.values()), {})
    for i in range(1, 5):
        label = first_seg.get(f"prepost_key{i}_label")
        question = first_seg.get(f"prepost_key{i}_question", "")
        scale = first_seg.get(f"prepost_key{i}_scale", "")
        if label:
            lines.append(f'  {{key:"pp{i}",label:{json.dumps(str(label))},question:{json.dumps(str(question or ""))},scale:{json.dumps(str(scale or ""))}}},')
    lines.append("];")
    lines.append("")

    # Theme colors
    lines.append("export const THEME_COLORS = {")
    for theme, color in theme_colors.items():
        c = color if color.startswith("#") else f"#{color}"
        lines.append(f'  {json.dumps(theme)}:{json.dumps(c)},')
    lines.append("};")
    lines.append("")

    # Tier config & helpers
    lines.append('export const TIER_CONFIG = {')
    lines.append('  1: { bg:"#064e3b", text:"#6ee7b7", accent:"#34d399", label:"TIER 1" },')
    lines.append('  2: { bg:"#854d0e", text:"#fde047", accent:"#eab308", label:"TIER 2" },')
    lines.append('  3: { bg:"#991b1b", text:"#fca5a5", accent:"#ef4444", label:"TIER 3" },')
    lines.append('};')
    lines.append("")
    lines.append("export function getTierNum(roi) { return roi >= 1.07 ? 1 : roi >= 1.00 ? 2 : 3; }")
    lines.append("")
    lines.append("export const PERSUADABILITY_LABELS = [\"Strong support\",\"Lean support\",\"Persuadable\",\"Lean oppose\",\"Strong oppose\"];")

    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) < 2:
        print("Usage: python convert_study.py <workbook.xlsx>")
        sys.exit(1)

    fname = sys.argv[1]
    print(f"Reading {fname}...")
    wb = openpyxl.load_workbook(fname, data_only=True)

    meta = read_meta(wb)
    messages = read_messages(wb)
    variant_text = read_variant_text(wb)
    control_sop = read_sop_matrix(wb, "ControlSoP")
    variant_sop = read_sop_matrix(wb, "VariantSoP")
    sig_control = read_sig_flags(wb, "SigFlags_Control")
    sig_variant = read_sig_flags(wb, "SigFlags_Variant")
    seg_metrics = read_segment_metrics(wb)
    theme_colors = read_theme_colors(wb)

    js = build_study_js(meta, messages, variant_text, control_sop, variant_sop,
                        sig_control, sig_variant, seg_metrics, theme_colors)

    out_path = "src/data/study.js"
    with open(out_path, "w") as f:
        f.write(js)

    n_msgs = len(messages)
    n_tokens = sum(len(m["tokens"]) for m in messages.values())
    print(f"Generated {out_path}: {n_msgs} messages, {n_tokens} token variants")
    print("Done.")


if __name__ == "__main__":
    main()
